### PR TITLE
Pull request Encounter, Auditevent and Location resources

### PR DESCRIPTION
**Pull request by JonasBacker**
Made the Encounter and Location FHIR resources with updates in the README and types required.

### CODE REVIEW

**Comment by sureshHARDIYA** [comment]
@ JonasBacker please update this PR, in order to be merged into master.

**Comment by sureshHARDIYA** [comment]
@JonasBacker  if you want this PR to be merged, please, 
- validate the PR by adding some example in the wiki
- Update from the master branch. 


If this PR is stale, please, close and delete the branch.

**Comment by JonasBacker** [comment]
Hi Suresh,
The examples should already in the wiki.
I also tried pulling but seems like I'm already at the latest branch if this is what you are refering to with: "Update from the master branch."
I also have not made any changes, so i cannot commit just nothing?

________________________________
Fra: Suresh KUMAR Mukhiya <notifications@github.com>
Sendt: onsdag 29. januar 2020 16:48
Til: sureshHARDIYA/intromat-fhir <intromat-fhir@noreply.github.com>
Kopi: JonasBacker <jonas_15_10_92@hotmail.com>; Mention <mention@noreply.github.com>
Emne: Re: [sureshHARDIYA/intromat-fhir] Pull request Encounter, Auditevent and Location resources (#15)


@JonasBacker<https://github.com/JonasBacker> if you want this PR to be merged, please,

  *   validate the PR by adding some example in the wiki
  *   Update from the master branch.

If this PR is stale, please, close and delete the branch.

**Comment by sureshHARDIYA** [comment]
- The image above means there is conflict in the `README.md` file. You need to fix that. 
Screenshot 2020-01-30 at 10 35 10
- By "Update from the master branch.", I mean you have to pull the latest code from the master branch and merge it into your branch and then push. I can see it does not have the latest code.

**Comment by sureshHARDIYA** [comment]
https://help.github.com/en/desktop/contributing-to-projects/syncing-your-branch

Please follow the link above.

**Pull request merged**
